### ISSUE TITLE
Error: Formula for Cosine Learning Rate Policy

### ISSUE THREAD

**Issue by stalhabukhari** [git-disl/LRBench#1]
Code for [Cosine Learning Rate Policy](https://github.com/git-disl/LRBench/blob/master/LRBench/lr/LRfunctions.py#L78) should instead be:
```
(k1 - k0) * 0.5 * (1 + math.cos(math.pi * 2 * iter / l)) + k0
```
in accordance with the mathematical expression given in Table I of your [paper](https://arxiv.org/abs/1908.06477v2)

**Comment by YanzhaoWu** [comment]
Sorry about that. L represents the half period. And we will correct it. Thanks.
