### ISSUE TITLE
Absolute Operator for the difference term

### ISSUE THREAD

**Issue by stalhabukhari** [git-disl/LRBench#2]
Hi!

I observed you used an **absolute** operator on the difference term in *equation 2* of the [paper](https://arxiv.org/abs/1908.06477v2) which provides a general formulation of LR policies, reiterated below:

<img src="https://latex.codecogs.com/svg.latex?\eta(t)&space;=&space;|k_0&space;-&space;k_1|&space;g(t)&space;&plus;&space;min(k_0,&space;k_1)" title="\eta(t) = |k_0 - k_1| g(t) + min(k_0, k_1)" />

My concern is that I am unable to find this operator anywhere in the [LRfunctions.py](https://github.com/git-disl/LRBench/blob/master/LRBench/lr/LRfunctions.py) file.

**Comment by YanzhaoWu** [comment]
A good question. This formula is a general form of cyclic learning rate (LR) functions, representing different cases, either k0 > k1 or k0 < k1. For a specific LR function, such as TRI, we have k0 < k1, so we can just remove this absolute operator.

**Comment by stalhabukhari** [comment]
Thank you for clarification!
