### ISSUE TITLE
CNN3 architecture (mentioned in paper)

### ISSUE THREAD

**Issue by stalhabukhari** [git-disl/LRBench#4]
Hi,

I tried to search for the **CNN3** architecture mentioned in the [paper](https://arxiv.org/pdf/1908.06477v2.pdf), but couldn't find anything online or in the cited references. Kindly point out the specific resource/paper that discusses this architecture.

Regards,
Talha

**Comment by YanzhaoWu** [comment]
Thank you very much for your interest in this project.

The CNN3 architecture for CIFAR-10 was derived from the Caffe official examples. Here is the model definition file: https://github.com/git-disl/LRBench/blob/master/examples/cifar10/caffe/cifar10_train_test.prototxt

Best,
Yanzhao Wu

**Comment by stalhabukhari** [comment]
Thank you for the clarification!
