### ISSUE TITLE
Visualization of the Training Process with Different LRs

### ISSUE THREAD

**Issue by Tusharfaroque** [git-disl/LRBench#5]
Hello,
Thanks for sharing the code. 
How did you visualize those three LRs in fig.1,
Did you use the LRBench to do that or a different package?

**Comment by YanzhaoWu** [comment]
Thank you very much for your interest in this project.

We just use LRBench for the visualization of these LRs. Here is the Jupyter notebook for visualization: https://github.com/git-disl/LRBench/blob/master/visualizer/visualize_LRs.ipynb.

Best,
Yanzhao Wu
